### ISSUE TITLE
Depends type annotation

### ISSUE THREAD

**Issue by chrisgoddard** [Lancetnik/FastDepends#10]
Hi there!

Currently, the `Depends` type annotation has it returning an instance of `model.Depends`

```python
def Depends(
    dependency: Callable[P, T],
    *,
    use_cache: bool = True,
    cast: bool = True,
) -> model.Depends:
    return model.Depends(
        dependency=dependency,
        use_cache=use_cache,
        cast=cast,
    )

```
    
I wonder, wouldn't it make more sense if it returned `T` so that it passes the type checker when used in this way:

```python
def some_function(
    dependency: SomeClass = Depends(get_dependency)
):
```

When `get_dependency` returns an object of type `SomeClass`.

**Comment by Lancetnik** [comment]
For now it is passing the mypy checks, but, probably, it makes a sence indeed.
In this implementation I targeted to the original FastAPI [Depends](https://github.com/tiangolo/fastapi/blob/46d1da08da73d8b4100e709edab9d84aa6b6a203/fastapi/param_functions.py#L567) and `Any` in this case I like more cuz it need no to hack inner mypy checks (if we marks response as `T` we will have a real return type conflict)

**Comment by Lancetnik** [comment]
I need to think about it

**Comment by chrisgoddard** [comment]
No problem. FWIW, I'm getting an error in Pylance 
![Screenshot 2023-09-21 at 1 59 48 PM](https://github.com/Lancetnik/FastDepends/assets/4922472/80a6d69e-520d-443d-837e-b765724f33b5)

**Comment by Lancetnik** [comment]
I changed Depends return type to Any. This way you still have to specify your annotation manually, but any errors are impossible.
