### ISSUE TITLE
Drop anyio requirement

### ISSUE THREAD

**Issue by skewty** [Lancetnik/FastDepends#102]
This project's usage of anyio seems minimal and could likely be avoided.

A basic TaskGroup could likely be recreated with minimal code yourself or worked around using asyncio.wait and asyncio already has thread pool executor.

**Comment by Lancetnik** [comment]
I am using anyio to be compatible with **asyncio** and **trio** runtimes both. I don't want to prefer any concrete to allow users choose by themselves

**Comment by skewty** [comment]
Fair point. What about making trio support an optional dependency (`pip install fastdepends[trio]`) and having the default code path be asyncio. If they choose trio support then anyio is installed.

I think most now see Trio to modern CPython being like JQuery to modern JavaScript.
