### ISSUE TITLE
Validation of non-pydantic types?

### ISSUE THREAD

**Issue by chrisgoddard** [Lancetnik/FastDepends#2]
Hey there - love this package! Quick question - what's the best practice for having dependencies that aren't valid Pydantic types - for example, I'm using it to inject an API client like so:
```python
@inject
async def cancel_running_flow_runs(
    flow_name: str,
    client: PrefectClient = Depends(prefect.get_client)
):
```

I get the error `check that <class 'prefect.client.orchestration.PrefectClient'> is a valid pydantic field type`

Now I could remove the type hint and it would work but I'd lose type hints within the function. I might be missing something obvious in the docs but curious if there's a way to either add a new type or allow arbitrary types in arguments?

**Comment by chrisgoddard** [comment]
This is the workaround I'm currently using:

```python

def inject_prefect_client():
    client = prefect.get_client()
    yield client

@inject
@sync_compatible
async def cancel_running_flow_runs(
    flow_name: str,
    client=Depends(inject_prefect_client)
):
    # func body hack
    client: PrefectClient = client
    ...
 ```

**Comment by Lancetnik** [comment]
Hi there! Appritiate your Issue. Indeed, it's my bad.
Right now I release version `1.1.4` to fix this bug.
Now you can use `Depends(*, cast=False)` to ignore a function parameter by pydantic.
Now your code will works correct way

````python
@inject
async def cancel_running_flow_runs(
    flow_name: str,
    client: PrefectClient = Depends(inject_prefect_client, cast=False),
):
    ...
```
