### ISSUE TITLE
Removal of _contrib.CreateBaseModel seems backwards incompatible

### ISSUE THREAD

**Issue by reritom** [Lancetnik/FastDepends#51]
Due to another bug in FastStream https://github.com/airtai/faststream/issues/1087 I am trying to use older versions of FastStream. 

FastStream has FastDepends as a dep, pinned to >=2.x, <3  https://github.com/airtai/faststream/blob/ac6d0edd66ee61dca011a5b16198c3e91c485cff/pyproject.toml#L51

As the removal of _contrib.CreateBaseModel is done from 2.6.0 and 2.7.0, installs of older versions of faststream are now failing as they are defaulting to 2.7.0 but require the removed CreateBaseModel.

**Comment by Lancetnik** [comment]
You can install older FastStream versions with pinned FastDepedns like

```
faststream==0.2.X
fast-depends==2.6.0
```

But, you are right, I'll add a little release to restore this object and we can save it until people do not stop use older FastStream versions

**Comment by Lancetnik** [comment]
@reritom any **FastStream** version < 0.3.7 are working fine with **FastDepends** < 0.2.6

**Comment by Lancetnik** [comment]
And with **FastDepends** == 0.2.8 too
