### ISSUE TITLE
TypeError: CallModel.solve() got multiple values for argument 'self'

### ISSUE THREAD

**Issue by heroyooki** [Lancetnik/FastDepends#80]
I am getting the error while trying to execute tests/sync/test_class.py.

**Comment by Lancetnik** [comment]
So why all tests works correctly in CI?

**Comment by Lancetnik** [comment]
What python version are you using?

**Comment by heroyooki** [comment]
I am using 3.11.6 version. Which one would be applicable? Thank you.

**Comment by heroyooki** [comment]
![Uploading Screenshot 2024-03-07 at 21.16.58.png…]()

**Comment by heroyooki** [comment]
Thanks a lot!
